image: i386/ubuntu:xenial

stages:
  - build

variables:
  BYOND_MAJOR: "513"
  BYOND_MINOR: "1527"

before_script:
  - apt-get update -qq
  - apt-get --yes install build-essential unzip libc6:i386 libgcc1:i386 libstdc++6:i386 curl -qq
  - curl "http://www.byond.com/download/build/${BYOND_MAJOR}/${BYOND_MAJOR}.${BYOND_MINOR}_byond_linux.zip" -o byond.zip
  - unzip byond.zip
  - cd byond
  - make install
  - cd ..

build:
    stage: build
    script:
      - chmod +rwx ./insert_maps_in_dme.sh
      - ./insert_maps_in_dme.sh
      - DreamMaker ColonialMarinesALPHA.dme
    artifacts:
      paths:
        - ColonialMarinesALPHA.dmb
        - ColonialMarinesALPHA.rsc
      expire_in: 20min

test:
    stage: test
    script:
      - DreamDaemon ColonialMarinesALPHA.dmb -trusted -params "run_tests=1&verbose_tests=1" 2>&1 | tee test_logs.log
      - cat test_logs.log | tail -1 | grep -q "ALL TESTS SUCCEEDED"
